'{"env":{"deployment":{"image":"python:3.11","port":null,"docker_args":[],"startup_timeout":180.0,"pull":"missing","remove_images":false,"python_standalone_dir":"/root","platform":null,"type":"docker"},"repo":{"github_url":"https://github.com/celery/celery","base_commit":"7b4c4c3938385a994c346f6fa80ce87f4efc0001","clone_timeout":500.0,"type":"github"},"post_startup_commands":[],"post_startup_command_timeout":500,"name":"main"},"agent":{"name":"main","templates":{"system_template":"You
  are a helpful assistant that can interact with a computer to solve tasks.","instance_template":"<uploaded_files>\n{{working_dir}}\n</uploaded_files>\nI''ve
  uploaded a python code repository in the directory {{working_dir}}. Consider the
  following PR description:\n\n<pr_description>\n{{problem_statement}}\n</pr_description>\n\nCan
  you help me implement the necessary changes to the repository so that the requirements
  specified in the <pr_description> are met?\nI''ve already taken care of all changes
  to any of the test files described in the <pr_description>. This means you DON''T
  have to modify the testing logic or any of the tests in any way!\nYour task is to
  make the minimal changes to non-tests files in the {{working_dir}} directory to
  ensure the <pr_description> is satisfied.\nFollow these steps to resolve the issue:\n1.
  As a first step, it might be a good idea to find and read code relevant to the <pr_description>\n2.
  Create a script to reproduce the error and execute it with `python <filename.py>`
  using the bash tool, to confirm the error\n3. Edit the sourcecode of the repo to
  resolve the issue\n4. Rerun your reproduce script and confirm that the error is
  fixed!\n5. Think about edgecases and make sure your fix handles them as well\nYour
  thinking should be thorough and so it''s fine if it''s very long.","next_step_template":"OBSERVATION:\n{{observation}}","next_step_truncated_observation_template":"Observation:
  {{observation}}<response clipped><NOTE>Observations should not exceeded {{max_observation_length}}
  characters. {{elided_chars}} characters were elided. Please try a different command
  that produces less output or use head/tail/grep/redirect the output to a file. Do
  not use interactive pagers.</NOTE>","max_observation_length":100000,"next_step_no_output_template":"Your
  command ran successfully and did not produce any output.","strategy_template":null,"demonstration_template":null,"demonstrations":[],"put_demos_in_history":false,"shell_check_error_template":"Your
  bash command contained syntax errors and was NOT executed. Please fix the syntax
  errors and try again. This can be the result of not adhering to the syntax for multi-line
  commands. Here is the output of `bash -n`:\n{{bash_stdout}}\n{{bash_stderr}}","command_cancelled_timeout_template":"The
  command ''{{command}}'' was cancelled because it took more than {{timeout}} seconds.
  Please try a different command that completes more quickly."},"tools":{"filter":{"blocklist_error_template":"Operation
  ''{{action}}'' is not supported by this environment.","blocklist":["vim","vi","emacs","nano","nohup","gdb","less","tail
  -f","python -m venv","make"],"blocklist_standalone":["python","python3","ipython","bash","sh","/bin/bash","/bin/sh","nohup","vi","vim","emacs","nano","su"],"block_unless_regex":{"radare2":"\\b(?:radare2)\\b.*\\s+-c\\s+.*","r2":"\\b(?:radare2)\\b.*\\s+-c\\s+.*"}},"bundles":[{"path":"/Users/garychen/Desktop/RLL/SWE-agent/tools/registry","hidden_tools":[]},{"path":"/Users/garychen/Desktop/RLL/SWE-agent/tools/edit_anthropic","hidden_tools":[]},{"path":"/Users/garychen/Desktop/RLL/SWE-agent/tools/review_on_submit_m","hidden_tools":[]}],"env_variables":{},"registry_variables":{"USE_FILEMAP":"true","SUBMIT_REVIEW_MESSAGES":["Thank
  you for your work on this issue. Please carefully follow the steps below to help
  review your changes.\n\n1. If you made any changes to your code after running the
  reproduction script, please run the reproduction script again.\n  If the reproduction
  script is failing, please revisit your changes and make sure they are correct.\n  If
  you have already removed your reproduction script, please ignore this step.\n2.
  Remove your reproduction script (if you haven''t done so already).\n3. If you have
  modified any TEST files, please revert them to the state they had before you started
  fixing the issue.\n  You can do this with `git checkout -- /path/to/test/file.py`.
  Use below <diff> to find the files you need to revert.\n4. Run the submit command
  again to confirm.\n\nHere is a list of all of your changes:\n\n<diff>\n{{diff}}\n</diff>\n"]},"submit_command":"submit","parse_function":{"error_message":"Your
  output was not formatted correctly. You must always include one discussion and one
  command as part of your response. Make sure you do not have multiple discussion/command
  tags.\nPlease make sure your output precisely matches the following format:\nDISCUSSION\nDiscuss
  here with yourself about what your planning and what you''re going to do in this
  step.\n\n```\ncommand(s) that you''re going to run\n```\n","type":"thought_action"},"enable_bash_tool":true,"format_error_template":"Your
  output was not formatted correctly. You must always include one discussion and one
  command as part of your response. Make sure you do not have multiple discussion/command
  tags.\nPlease make sure your output precisely matches the following format:\nDISCUSSION\nDiscuss
  here with yourself about what your planning and what you''re going to do in this
  step.\n\n```\ncommand(s) that you''re going to run\n```\n","command_docs":"bash:\n  docstring:
  runs the given command directly in bash\n  signature: <command>\n  arguments:\n    -
  command (string) [required]: The bash command to execute.\n\nstr_replace_editor:\n  docstring:
  Custom editing tool for viewing, creating and editing files * State is persistent
  across command calls and discussions with the user * If `path` is a file, `view`
  displays the result of applying `cat -n`. If `path` is a directory, `view` lists
  non-hidden files and directories up to 2 levels deep * The `create` command cannot
  be used if the specified `path` already exists as a file * If a `command` generates
  a long output, it will be truncated and marked with `<response clipped>` * The `undo_edit`
  command will revert the last edit made to the file at `path`\nNotes for using the
  `str_replace` command: * The `old_str` parameter should match EXACTLY one or more
  consecutive lines from the original file. Be mindful of whitespaces! * If the `old_str`
  parameter is not unique in the file, the replacement will not be performed. Make
  sure to include enough context in `old_str` to make it unique * The `new_str` parameter
  should contain the edited lines that should replace the `old_str`\n\n  signature:
  str_replace_editor <command> <path> [<file_text>] [<view_range>] [<old_str>] [<new_str>]
  [<insert_line>]\n\n  arguments:\n    - command (string) [required]: The commands
  to run. Allowed options are: `view`, `create`, `str_replace`, `insert`, `undo_edit`.\n    -
  path (string) [required]: Absolute path to file or directory, e.g. `/testbed/file.py`
  or `/testbed`.\n    - file_text (string) [optional]: Required parameter of `create`
  command, with the content of the file to be created.\n    - old_str (string) [optional]:
  Required parameter of `str_replace` command containing the string in `path` to replace.\n    -
  new_str (string) [optional]: Optional parameter of `str_replace` command containing
  the new string (if not given, no string will be added). Required parameter of `insert`
  command containing the string to insert.\n    - insert_line (integer) [optional]:
  Required parameter of `insert` command. The `new_str` will be inserted AFTER the
  line `insert_line` of `path`.\n    - view_range (array) [optional]: Optional parameter
  of `view` command when `path` points to a file. If none is given, the full file
  is shown. If provided, the file will be shown in the indicated line number range,
  e.g. [11, 12] will show lines 11 and 12. Indexing at 1 to start. Setting `[start_line,
  -1]` shows all lines from `start_line` to the end of the file.\n\nsubmit:\n  docstring:
  submits the current file\n  signature: submit\n\n","multi_line_command_endings":{},"submit_command_end_name":null,"reset_commands":[],"execution_timeout":30,"install_timeout":300,"total_execution_timeout":1800,"max_consecutive_execution_timeouts":3},"history_processors":[{"type":"cache_control","last_n_messages":2,"last_n_messages_offset":0,"tagged_roles":["user","tool"]}],"model":{"name":"gemini/gemini-2.0-flash","per_instance_cost_limit":3.0,"total_cost_limit":0.0,"per_instance_call_limit":0,"temperature":0.0,"top_p":1.0,"api_base":null,"api_version":null,"api_key":null,"stop":[],"completion_kwargs":{},"convert_system_to_user":false,"retry":{"retries":20,"min_wait":10.0,"max_wait":120.0},"delay":0.0,"fallbacks":[],"choose_api_key_by_thread":true,"max_input_tokens":null,"max_output_tokens":null},"max_requeries":3,"action_sampler":null,"type":"default"},"problem_statement":{"path":"/var/folders/qr/35_8h8cj01ld2w97wfc_wpxh0000gn/T/tmpwd4qhan0","extra_fields":{},"type":"text_file","id":"celery__celery-8432"},"output_dir":"baselines/sweagent/sweagent_outputs","actions":{"open_pr":false,"pr_config":{"skip_if_commits_reference_issue":true},"apply_patch_locally":false},"env_var_path":null}'
